spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://postges.backend:5432/postgres
    username: postgres
    password: postgres
    name: telegram-prod-database
    driver-class-name: org.postgresql.Driver
    hikari:
      poolName: Hikari
      auto-commit: false
      maximum-pool-size: 50
      driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: false
    contexts: prod,dev
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
      hibernate.show_sql: false
      hibernate.format_sql: false
      hibernate.query.plan_parameter_metadata_max_size: 2000
      hibernate.query.plan_cache_max_size: 20000
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: false